---
sudo: false
language: rust
rust:
  - beta
  - nightly

script:
  - cargo test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
    secure: "l09JyptkyW3OOnkn62c+7UKOBwqbm62CdZtpW8scncXwgy3PLXUJKIOafxv7/7vk4Xr3skenv3PUQmzC11eVv5k68BPv/RFbx5Gp4kxn/rr5gyJUbFEBXEpx8zY68RBg1wT0vp+j9nDLUf5Rw5+V4PAptTxtG4/YSs8F3WbXNMw="
